# Do not render pages inside of iFrames to avoid clickjacking.
add_header X-Frame-Options SAMEORIGIN;

# Disable Content-Type sniffing in supported browsers.
add_header X-Content-Type-Options nosniff;

# Enable XSS Filter built into most browsers.
add_header X-XSS-Protection "1; mode=block";

# Disable URL indexing by crawlers (FOR DEVELOPMENT/STAGE! WILL KILL SEO!!)
add_header X-Robots-Tag none;

# Disable the option to "open" the file when downloading.
add_header X-Download-Options noopen;

