add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
# -----------------------------------------------------------------------------------------
# Disable URL indexing by crawlers (FOR DEVELOPMENT/STAGE! WILL KILL SEO!!)
# -----------------------------------------------------------------------------------------
# add_header X-Robots-Tag none;
# -----------------------------------------------------------------------------------------
# Disable the option to "open" the file when downloading.
# -----------------------------------------------------------------------------------------
add_header X-Download-Options noopen;
add_header X-Robots-Tag none;
# -----------------------------------------------------------------------------------------
# Disable the ability for other users to embed content from your website.
# -----------------------------------------------------------------------------------------
add_header X-Permitted-Cross-Domain-Policies none;